language: go
go:
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - 1.9
install:
  - go get -t -v ./...
notifications:
  email:
    recipients:
      - 43413875@qq.com
    on_success: change
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 7876afa3-e4db-4d94-970b-906a45a94b97