language: go
go:
  - 1.13
install:
  - go get -t -v ./...
notifications:
  email:
    recipients:
      - 43413875@qq.com
    on_success: change
    on_failure: always
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'