language: go
go:
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - 1.9
install:
  - go get -t -v ./...
notifications:
  email:
    recipients:
      - 43413875@qq.com
    on_success: change
    on_failure: always
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE flash-sale'